### PR TITLE
Include extra options in POST request 

### PR DESCRIPTION
**Pull request by ronaldotijucas**

### CODE REVIEW

**Comment by NickClark** [comment]
Is this being considered for merge? It's necessary to have traits and includes. Kind of surprised that the Hangar team isn't keeping their client lib up to date. Are people using something else that I haven't come across?

**Comment by rossmeissl** [comment]
@NickClark sorry for the delay!

**Comment by NickClark** [comment]
Wow, no delay on my end. I basically just clicked the comment button :smile:

**Comment by NickClark** [comment]
When might we expect a new NPM release?

**Comment by rossmeissl** [comment]
@NickClark I actually don't know how to do that and our primary dev @devTristan on this is on vacation until tomorrow!

**Comment by NickClark** [comment]
Ok, NP, I'll just install from the repo directly for now. Thanks.

**Pull request merged**
